name: CI

on: [push]

jobs:
  sast_scan:
    name: running bandit scan
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install bandit
      run: pip install bandit
    - name: Running Bandit scan 
      run: bandit -r -ll -ii -f json -o bandit_report.json.
    - name: Exporting artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with: 
        name: bandit_findings
        path: bandit_report.json
